# Site settings
title : dust
tagline: 'Data Assimilation for Agent-Based Modelling'
author :
  name : Nick Malleson
  github : nickmalleson
  twitter : nickmalleson
keywords: big data, agent-based modelling, simulation, urban flows, urban analytics


description: > # this means to ignore newlines until "baseurl:"
    This is the website for the dust project, developing methods to support city simulation
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://urban-analytics.github.io/dust/" # the base hostname & protocol for your site
twitter_username: nickmalleson
github_username:  nickmalleson
email: n.s.malleson@leeds.ac.uk

# Build settings
markdown: kramdown
