# Site settings
title : dust
tagline: 'Data Assimilation for Agent-Based Modelling'
author :
  name : Nick Malleson
  github : nickmalleson
  twitter : nickmalleson
keywords: big data, agent-based modelling, simulation, urban flows, urban analytics


description: > # this means to ignore newlines until "baseurl:"
    This is the website for the dust project, developing methods to support city simulation

#baseurl: "https://urban-analytics.github.io/dust" # the subpath of your site, e.g. /blog/
baseurl: /dust
url: https://urban-analytics.github.io

twitter_username: nickmalleson
github_username:  nickmalleson
email: n.s.malleson@leeds.ac.uk


# Define how blog permalinks should be constructed
permalink: /:year/:month/:title.html
# (the default:)
#permalink: /:categories/:year/:month/:day/:title.html

# Build settings
markdown: kramdown

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

